### ISSUE TITLE
MemcacheCache Contains failes for 0 value

### ISSUE THREAD

**Issue by jaypea** [doctrine/common#101]
the _doContains() Implementation in Doctrine\Common\Cache\MemcacheCache returns false if there is a element in the cache with value === 0.
It should return true in those cases since the element in the cache exists.
my workaround is:
```protected function _doContains($id)
    {
        $content =$this->_memcache->get($id);
        return ($content === 0 || (bool) $content);
    }

```
```

**Comment by ostrolucky** [comment]
This is oldest open issue and it has been fixed in https://github.com/doctrine/cache/pull/67

So I think it's safe to close this @jaypea @Ocramius

**Comment by lcobucci** [comment]
@ostrolucky thanks for pointing this out, closing...
