### ISSUE TITLE
updating an service with composer update gives me this error/problem

### ISSUE THREAD

**Issue by rozemarijn56** [doctrine/common#1010]
Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#3162
!!    #message: """
!!      Attempted to load interface "Reader" from namespace "Doctrine\Common\Annotations".\n
!!      Did you forget a "use" statement for another namespace?
!!      """
!!    #code: 0
!!    #file: "./vendor/jms/serializer/src/Metadata/Driver/AttributeDriver/AttributeReader.php"
!!    #line: 16
!!    trace: {
!!      ./vendor/jms/serializer/src/Metadata/Driver/AttributeDriver/AttributeReader.php:16 { …}
!!      ./vendor/symfony/error-handler/DebugClassLoader.php:294 { …}
!!      Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() {}
!!      ./vendor/jms/serializer-bundle/DependencyInjection/JMSSerializerExtension.php:141 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/ConfigurableExtension.php:35 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
!!      ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:42 { …}
!!      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
!!      ./vendor/symfony/dependency-injection/ContainerBuilder.php:716 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:538 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:767 { …}
!!      ./vendor/symfony/http-kernel/Kernel.php:128 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:166 { …}
!!      ./vendor/symfony/framework-bundle/Console/Application.php:72 { …}
!!      ./vendor/symfony/console/Application.php:171 { …}
!!      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
!!      ./vendor/autoload_runtime.php:29 { …}
!!      ./bin/console:11 {
!!        › 
!!        › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
!!        › 
!!        arguments: {
!!          "/var/www/vendor/autoload_runtime.php"
!!        }
!!      }
!!    }
!!  }
!!  2024-03-25T09:47:46+00:00 [critical] Uncaught Error: Interface "Doctrine\Common\Annotations\Reader" not found
!!

**Comment by derrabus** [comment]
This is not a support forum. Consider taking your question here:

* https://github.com/symfony/symfony/discussions/
* https://github.com/doctrine/orm/discussions/
