### ISSUE TITLE
Remove setOption() line from RedisCache

### ISSUE THREAD

**Issue by kipelovets** [doctrine/common#155]
In Doctrine\Common\Cache\RedisCache#setRedis() there is a line that modifies provided Redis object's serializer type:

```
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);
```

That is in issue if this Redis object is shared with other subsystems which access this Redis instance before the call to RedisCache#setRedis, or there are other projects that access the same Redis server and use another type of serializer. 

Using different serializers with one Redis server is not a good idea as it can result in corrupted data. This code with Redis objects $redis and $redis2 connected to the same database:

```
$redis->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_IGBINARY);
$redis->set('set',1);
var_dump($redis->get('set'));
var_dump($redis2->get('set'));
```

produces output:

```
int(1)
string(6) "\000\000\000\002\006\001"
```

It is also a bad idea to modify cache driver settings inside CacheProvider. No other class that extend CacheProvider does such things

**Comment by ostrolucky** [comment]
@kipelovets @Ocramius This can be closed, as this is no longer issue with doctrine/common and there are already opened issues and pull requests regarding this in doctrine/cache
