### ISSUE TITLE
"Cannot redeclare class ...\Annotation" when an interface named Annotation exists

### ISSUE THREAD

**Issue by arnaud-lb** [doctrine/common#192]
When an interface whose name is *Annotation* exists in the same namespace than an annotation, the DocParser attempts to load `namespace\Annotation`, which results in a `Cannot redeclare class ...\Annotation` error.

Example from ORM:

```
<?php
namespace Doctrine\ORM\Mapping;

/**
 * @Annotation
 * @Target("CLASS")
 */
final class Table implements Annotation
{
```

```
<?php
namespace Doctrine\ORM\Mapping;

interface Annotation
{
```

**Comment by guilhermeblanco** [comment]
I'm closing this issue as it looks like it might have been solved years ago. Please reopen if issue still persists.
