### ISSUE TITLE
Move CommitOrderCalculator to Common

### ISSUE THREAD

**Issue by nfx** [doctrine/common#201]
What exists now:

* https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Internal/CommitOrderCalculator.php
* https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Internal/CommitOrderCalculator.php

Almost with the same content. 

What is desired:

* in order not to create new JPA implementation based on doctrine-common, as a developer i won't need to copy-paste a class from there.

**Comment by guilhermeblanco** [comment]
-1, closing.

**Comment by Ocramius** [comment]
Removed milestone, since the issue is a `won't fix`
