### ISSUE TITLE
Allow comments inside annotations

### ISSUE THREAD

**Issue by mikeyp** [doctrine/common#264]
*Yes*, I know how this sounds and, *Yes*, I am serious.

In some annotations it'd be nice to be able to add a comment or note about specific values defined as part of the annotation. For example:

```php
<?php
/**
 * @ORM\Column(type="string")
 * @Assert\NotEmpty // This is a special snowflake because blah blah blahhh yadda blah.
 * @Assert\Email
 * @var string
 */
```

I don't think we need to support /** */ inside of comments as I'm pretty sure that would break most PHP implementations. Ideally these could work on any line within an annotation and would follow existing standards for comments.

**Comment by guilhermeblanco** [comment]
I assume since you're ALREADY in a comment, there shouldn't have any issue than detailing issues outside of the block.

Closing this as won't fix, because it really doesn't make sense to me.

**Comment by joachim-n** [comment]
The idea here is to be able to add comments that relate specifically to a given line, as in the OP's example.

Adding comments like this outside of the block really isn't viable if the block is large. In Drupal, we routinely have blocks which are 50+ lines, for example: https://api.drupal.org/api/drupal/core!modules!node!src!Entity!Node.php/class/Node/8

**Comment by Ocramius** [comment]
Removed milestone - it's not fixed.

**Comment by joachim-n** [comment]
I don't understand why this has been closed as won't fix.

As I explained above, in a very large annotation, commenting above or below the annotation really isn't a good solution. There is therefore a clear use case for this.

**Comment by Ocramius** [comment]
@joachim-n I'm fine with re-evaluating this if somebody writes a patch and careful tests around it. I just fixed the status, since the milestone was incorrectly assigned.

**Comment by MurzNN** [comment]
We need comments in annotation comments, for example, to in-place describe some value in more detail, or to temporary comment-out some values without deleting them from file. Will be good to have something like this:
```
/**
 * Checks if a user name is unique on the site.
 *
 * @Constraint(
 *   id = "UserNameUnique", // The name field of currently logged in user
 *   // name = @Translation("User name legacy", context = "Validation"),
 *   label = @Translation("User name unique", context = "Validation"),
 * )
 */
```
or:
```
/**
 * Checks if a user name is unique on the site.
 *
 * @Constraint(
 *   id = "UserNameUnique", # The name field of currently logged in user
 *   # name = @Translation("User name legacy", context = "Validation"),
 *   label = @Translation("User name unique", context = "Validation"),
 * )
 */
