### ISSUE TITLE
Criteria should filter by 'LIKE' comparison

### ISSUE THREAD

**Issue by chrisoconnell** [doctrine/common#286]
Example usage would be:

$criteria = Criteria::create()
    ->where(Criteria::expr()->like("title", "%test%"))

There should be a `like` and `ilike` expression for doing case sensitive and insensitive comparisons respectively. 

I would be happy to contribute to the code which does that if you agree that this functionality should be added to doctrine/common.

**Comment by baptistedonaux** [comment]
CONTAINS is ambiguous. Developpers searchs the LIKE constant. Thank you @jankramer for this response.

**Comment by apoberez** [comment]
Hello, Is there any way to get 'text%' instead '%text%'? 
 <code>Criteria::expr()->contains('lastName', $lastName);</code>
hardcoded: 
<code>case Comparison::CONTAINS:</code>
               <code> $parameter->setValue('%' . $parameter->getValue() . '%', $parameter->getType());</code>

we cannot use default case because operator map don't include 'like'

---
private static $operatorMap = array(
        Comparison::GT => Expr\Comparison::GT,
        Comparison::GTE => Expr\Comparison::GTE,
        Comparison::LT  => Expr\Comparison::LT,
        Comparison::LTE => Expr\Comparison::LTE
    );

**Comment by stof** [comment]
@jmikola the issue with regex matching is that it may be much more complex to implement cross-platforms (do they all support regexes ? and if yes, do they use the same syntax for them ?).

I think supporting the LIKE syntax is easier to make cross-platforms (the ODM could just convert it to a regex and use regex matching to implement it)

**Comment by apoberez** [comment]
You are right about cross-platforms, but question is different. Why in this case we can't make first '%' optional, maybe additional optional argument:
expr()->contains('lastName', $lastName, true)

'text%' is much faster on large tables than '%test%', because index can be used in second case all rows will be checked on large table it's too slow.

**Comment by EnricoGsell** [comment]
I also think what apoberez mentioned would be a nice feature. 
But instead of having flag I would prefer a new method (and also one for ends with):

    expr()->startsWith('lastName', $lastName);
    expr()->endsWith('lastName', $lastName);
