### ISSUE TITLE
Possible bug in the __construct of ArrayCollection

### ISSUE THREAD

**Issue by betomoretti** [doctrine/common#289]
I had this error when i tried to instantiate an ArrayCollection:

 [Symfony\Component\Debug\Exception\ContextErrorException]  
 Catchable Fatal Error: Argument 1 passed to Doctrine\Common\Collections\ArrayCollection::__construct() must be of the type array, object given, called in vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 528 and defined in vendor/doctrine/common/lib/Doctrine/Common/Collections/  
 ArrayCollection.php line 48

The only solution that worked out for my was deleting this array from the contructor's arguments.

public function __construct(array $elements = array())
   {
       $this->_elements = $elements;
   }

 I am using Symfony2.

**Comment by ostrolucky** [comment]
This problem has obviously been caused by wrong fixture file, where value has been specified instead of an list. I think this issue is safe to close @betomoretti @Ocramius @stof

**Comment by lcobucci** [comment]
@ostrolucky yeap.

Closing as `invalid` as per @ostrolucky's review...

**Comment by zullieh** [comment]
Hi, I was have the same problem, and my solution was in "the controller" 
I mean, I called at $productList->setIdProduct($product); 
obviously with my classes and these make the error cause I tryed call the idProduct() in $productList...
