### ISSUE TITLE
Undefined class constant 'self::STATE_PROCESSING' :  ProxyGenerator.php

### ISSUE THREAD

**Issue by fundup** [doctrine/common#346]
Hello,
I have an this error when I do a cache clear in prod environement :
Undefined class constant 'self::STATE_PROCESSING' in XXX/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php on line 918

I'm using symfony 2.5.6 and doctrine-bundle 1.3-beta2.

**Comment by ostrolucky** [comment]
This is general issue with symfony cache. https://github.com/symfony/symfony/issues/22243
This isn't a doctrine bug, but symfony one. Therefore, this issue can be closed @Ocramius

**Comment by Ocramius** [comment]
@ostrolucky thanks!
