### ISSUE TITLE
doctrine/annotations AnnotationsRegistry::registerNamespace unexpected behaviour

### ISSUE THREAD

**Issue by prumand** [doctrine/common#360]
giving a namespace and a path to registerNamespace, I would expect it to load the class from the path given + any extra namespace of the class. But it's not:

e.g.
```php
 AnnotationsRegistry::registerNamespace('MyProject', 'my/project/path');
```
would result in a path for class MyProject\Annotation like
```
my/project/path/MyProject\Annotation
```
rather than:
```
my/project/Annotation
```

lg

**Comment by Ocramius** [comment]
@prumand we support PSR-0 directory structures, not PSR-4 structures.

**Comment by prumand** [comment]
Ah, ok I thought it would be prs-4 because of the missing underscore replacement.

thx
