### ISSUE TITLE
Warning with php rename function, in ProxyGenerator class

### ISSUE THREAD

**Issue by clemgrim** [doctrine/common#362]
Hello,

Sometimes i got a warning with the `rename` function, called in `Doctrine\Common\Proxy\ProxyGenerator:305`

```
Warning: rename(C:\Windows\TEMP\__CG__AppEntitiesCategory.php.551eee3a298629.89032411,C:\Windows\TEMP\__CG__AppEntitiesCategory.php)
```

I got this warning when I send multiple xhr request, so i guess there is a conflict with temporaries files ?

I temporarily fixed this by adding a `@` before the function call to disable error, but i hope there's a better way to fix this

Note: I got the same warning when I configure a specific cache directory

```php
// this directory exists and is writeable
Setup::createConfiguration($isDevMode, __DIR__.'/../../cache/doctrine');
```

**Comment by Ocramius** [comment]
On windows, `tempnam()` is not really reliable: I'm afraid that we can't fix this bug ourselves.

I suggest you to generate proxies upfront, or to evaluate proxies at runtime by using [`AbstractProxyFactory::AUTOGENERATE_EVAL`](https://github.com/doctrine/common/blob/ad89591bebea6490fd589f872d0a9ef63e9674a9/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php#L70), which doesn't write to disk.

You can set this flag on the [`Configuration` object](https://github.com/doctrine/doctrine2/blob/2c9093006897eb73d27a6c43beb0a9e3db1d1c88/lib/Doctrine/ORM/Configuration.php#L94)

**Comment by zeroedin-bill** [comment]
@Ocramius I think this is actually because the proxy generator doesn't check if the destination file already exists. Basically this is a race condition in the proxy generator. Two requests were trying to generate proxies simultaneously. One of the requests wins, and the other throws a warning because the file already exists.

**Comment by clemgrim** [comment]
@Ocramius thank you, I prefer use the `AbstractProxyFactory::AUTOGENERATE_NEVER` mode, and generate proxy once via the console.
I didn't know it was possible and it solve my problem, thank's a lot !
