### ISSUE TITLE
Add getEventManager method to ObjectManager interface?

### ISSUE THREAD

**Issue by Wilt** [doctrine/common#363]
Both the [`EntityManager`](http://www.doctrine-project.org/api/orm/2.0/class-Doctrine.ORM.EntityManager.html#_getEventManager) and the [`DocumentManager`](http://www.doctrine-project.org/api/mongodb_odm/1.0/class-Doctrine.ODM.MongoDB.DocumentManager.html#_getEventManager) have a `getEventManager` method. But the ObjectManager interface does not have this `getEventManager` method. 

Is this on purpose or would it be possible to add this method to the interface? 

I often try to keep my PHPdoc based on the common `ObjectManager` but when using `getEventManager` the method is marked as invalid and not type hinted in my code editor.

**Comment by Ocramius** [comment]
> Is this on purpose or would it be possible to add this method to the interface? 

It is on purpose.
A getter does not expose behavior, and therefore should (most probably) not be interfaced on an object that isn't a newable.

The fact that we expose `getRepository()` is already a flaw.

**Comment by Wilt** [comment]
Okay thanks...

**Comment by stof** [comment]
@Ocramius ``getRepository`` is a bit special IMO in the current architecture, given that getting the repository requires access to the EntityManager to build it, and the EntityManager is the main doctrine entry point. Fixing it would require first that we break the cyclic object graph of Doctrine (i.e. avoiding that lower level components depend on the high-level API everywhere for instance).

However, I agree with you there. there is no reason for the ObjectManager to expose a getter for its dependency (and if we rework the object graph in Doctrine 3, the getter may even be removed from EntityManager at some time)

**Comment by Ocramius** [comment]
> `getRepository` is a bit special IMO in the current architecture

It's a `ServiceLocator` hidden in plain sight.

We had it since a long time, so it's probably not going to change in future anyway.
