### ISSUE TITLE
Incorrect and missing API documentation (for 2.4) regarding Cache namespace

### ISSUE THREAD

**Issue by farzadghanei** [doctrine/common#365]
As I followed the [API documentation](http://www.doctrine-project.org/api/common/2.4/namespace-Doctrine.Common.Cache.html) for Cache name space I found there should be an `AbsrtractCache` class, but there is no such class in reality; Instead `CacheProvider` is the abstract parent class for implementations. Also there are far more implementations available (Including `VoidCache` which I needed and I implemented myself, extending `AbstractCache`) that are missing from the documentation, like `VoidCache`, `FileSystemCache`, `RedisCache`, `RiakCache`, etc.

**Comment by Ocramius** [comment]
That API doc seems totally outdated: we moved cache out of common ages ago...

**Comment by beberlei** [comment]
Cache is not its own API project because its not listed in projects.yml of the website. We need to fix that for all new components.

**Comment by Majkl578** [comment]
API docs for Cache are now available here: https://www.doctrine-project.org/api/cache/latest/index.html
It is also documented as a separate component now: https://www.doctrine-project.org/projects/cache.html
