### ISSUE TITLE
Class 'Doctrine\Common\Inflector\Inflector' not found

### ISSUE THREAD

**Issue by Baft** [doctrine/common#378]
class 'Doctrine/Common/Util/Inflector'  use 'Doctrine\Common\Inflector\Inflector' as baseInflector
that dose not exist !

**Comment by Baft** [comment]
inflector folder dose not exit in this repo .
with composer , inflector folder exist  out of Common folder .
solve with autoloader . but it is correct ?

**Comment by Ocramius** [comment]
It's in https://github.com/doctrine/inflector/blob/63c61ba4f8f20c9a013e0fb5b6c0a8d0002f87a9/lib/Doctrine/Common/Inflector/Inflector.php

**Comment by menriquez** [comment]
I'm getting this error currently as I am trying to migrate a laravel project from Linux to windows.

i cant really figure out what I am supposed to do with this info...should I change the path in my code or was the issue supposed to have been fixed?

**Comment by menriquez** [comment]
@Ocramius so what is your solution to the problem?  just copy the code to the correct location?  shouldnt there be a better fix then that?

**Comment by jmikola** [comment]
Using the most recent releases as an example:

 * [2.8.1](https://github.com/doctrine/common/releases/tag/v2.8.1) of `doctrine/common` (this library)
 * [1.2.0](https://github.com/doctrine/inflector/releases/tag/v1.2.0) of `doctrine/inflector`

This library contains [`Doctrine\Common\Util\Inflector`](https://github.com/doctrine/common/blob/v2.8.1/lib/Doctrine/Common/Util/Inflector.php), which extends [`Doctrine\Common\Inflector\Inflector`](https://github.com/doctrine/inflector/blob/v1.2.0/lib/Doctrine/Common/Inflector/Inflector.php) in the `doctrine/inflector` package. This library also [depends on `doctrine/inflector` 1.x](https://github.com/doctrine/common/blob/v2.8.1/composer.json#L17), so installing `doctrine/common` via Composer should pull in `doctrine/inflector`.

If the class is missing, there is either an unresolved dependency (which Composer should report) or autoloading is misconfigured.

**Comment by menriquez** [comment]
@jmikola thank you for your assistance.  yes it would seem in my case that autoloading was misconfigured.

i am new to laravel and am still getting my head around its design and dir scaffolding, so any help along those lines would be of great assistance.

**Comment by Ocramius** [comment]
Given composer, no autoloading setup should be needed at all.

**Comment by e-hop** [comment]
i'm having the same issue in laravel 7.11

**Comment by alcaeus** [comment]
Since you commented on the Laravel PR that allowed for 2.0 being introduced I’m sure you’re aware that this is not related to the original issue. Closing and locking as resolved.
