### ISSUE TITLE
Exclude tests from dist

### ISSUE THREAD

**Issue by kachkaev** [doctrine/common#379]
I'm using doctrine in a symfony project and get it via composer with ```--prefer-dist``` option. This type of installation also grabs the tests in ```doctrine/common```, which causes eclipse PHP builder to flag an error:

![screen shot 2015-09-03 at 13 12 13](https://cloud.githubusercontent.com/assets/608862/9657905/1f05f3b2-523d-11e5-8e5e-8933277ca234.png)

_[VariadicTypeHintClass.php](https://github.com/doctrine/common/blob/master/tests/Doctrine/Tests/Common/Proxy/VariadicTypeHintClass.php) has got some PHP5.6-specific syntax, while the whole repository seems to be still compatible with 5.3 (according to [composer.json](https://github.com/doctrine/common/blob/master/composer.json))._

Sometimes a special ```.gitattributes``` file is added to the project root dir, which forces github to exclude certain folders from the zip archives that are being fetched by composer. This is done [in Doctrine2](https://github.com/doctrine/doctrine2/blob/master/.gitattributes), for example.

Could the same practice be applied in ``doctrine/common``?

**Comment by Ocramius** [comment]
@kachkaev send a PR to exclude the tests. It's not a real bug though, so I'm closing this one.
