### ISSUE TITLE
Discriminator fields and peristent type fields should not be mutually exclusive

### ISSUE THREAD

**Issue by Bilge** [doctrine/common#392]
Presently, if a field is marked as a persistent type and a discriminator field, it will only be persisted and hydrated but will not act as a discriminator. This creates an anti-pattern of duplicating the discriminator field's content in order to use the data as both a discriminator and an accessible field.

This appears to be a [common problem](http://stackoverflow.com/questions/4450381/can-i-access-discriminator-field-from-php-in-doctrine2). When a field is marked as a discriminator it should still be possible to hydrate it.

**Comment by Ocramius** [comment]
This is intended behavior: discriminator fields are not supposed to be mapped as entity fields, and instead are supposed to just be translated into the type of the fetched value.

Allowing discriminators to be mapped as fields would also lead to the possibly catastrophic situation where people change the discriminator post-instantiation, which implies a cast, which is an unsupported functionality (and will stay unsupported, as the discriminator is part of the identifier).
