### ISSUE TITLE
your latest release 2.6 forces dbal and orm backwards

### ISSUE THREAD

**Issue by guyradford** [doctrine/common#395]
when composer upgraded to doctrine/common v2.6.0, it forced doctrine/dbal back  to v2.4.4 and doctrine/orm back to v2.4.8. This broke loads of stuff.
Thank you

Fix
to temporarily get round this I have forced composer to use doctrine/common v2.5.1

**Comment by Ocramius** [comment]
Shouldn't you simply force the correct orm/dbal versions?

**Comment by Ocramius** [comment]
@crazylime never mind, just noticed that ORM and DBAL will need a release to accept 2.6.x here.
