### ISSUE TITLE
2.5 => 2.6 why minor?

### ISSUE THREAD

**Issue by rbalazs** [doctrine/common#704]
The commit introduced code depending on a "new" language feature (Short Array Syntax / php 5.4), trivially breaking backward compatibility. The minor version bump is defendable, because it not about the doctrine API, rather about the legacy eco, but still, why not raise major (aka. breaking) version? It would have notified the package managers to avoid the new version, because it might break the existing system. I am curios about your opinion. Thank you for any help you can provide!

**Comment by Ocramius** [comment]
A dependency bump to the PHP version is not to be considered a BC break: it's a dependency like any other, and if your system doesn't support it, then you won't be allowed to upgrade to it anyway.
