### ISSUE TITLE
Cannot find Criteria class in online api doc

### ISSUE THREAD

**Issue by towertop** [doctrine/common#705]
I followed the link in [Doctrine projects list](http://www.doctrine-project.org/projects.html) to [Common's API doc ](http://www.doctrine-project.org/api/common/2.5/index.html) .

And I searched but found no api doc for the class Doctrine\Common\Collections\Criteria . But confirmed its source code has phpdoc.

**Comment by Ocramius** [comment]
I think the problem is that the docs you are reading there are for 2.3, whereas they should point at the 2.5 docs.
Please consider re-opening this issue against https://github.com/doctrine/doctrine-website-sphinx.
