### ISSUE TITLE
v2.6.1 - Proxy::class reference in ProxyGenerator.php file

### ISSUE THREAD

**Issue by pbrinkfhg** [doctrine/common#707]
Version 2.6.1.

In ProxyGenerator.php line 62 there is a reference to Proxy::class. 
There is no class variable called class in the Proxy class in lib/Doctrine/Common/Proxy/Proxy.php.
I received an error while using Doctrine with Symfony2.
Changing line 62 to `'baseProxyInterface'   => 'Doctrine\Common\Proxy\Proxy',` fixes my issues.
I can provide more information about my setup but this seems like a simple fix.

**Comment by Ocramius** [comment]
2.6 requires PHP 5.5
