### ISSUE TITLE
how to use doctrine class loader for twig template engine

### ISSUE THREAD

**Issue by roji430** [doctrine/common#708]
how add twig class to doctrine classloader 
Thanks in advance
issue: Twig use prefix Twig and namespace separator '_'

**Comment by stof** [comment]
You cannot. the Doctrine ClassLoader is not a PSR-0 loader. I supports only a subset of PSR-0, and Twig uses some of the rules unsupported by the Doctrine ClassLoader.

Use an autoloader which supports the PSR-0 standard.
Composer provides one for you automatically when you install packages with Composer. and if you don't use Composer, you can use the Symfony ClassLoader component for instance, which provides such autoloader (and a few others): https://github.com/symfony/class-loader

**Comment by roji430** [comment]
Thank you @stof

**Comment by stof** [comment]
Well, actually, a Doctrine ClassLoader can be configured to autoload Twig too (as Twig itself also uses a subset of PSR-0). But you will need a separate instance than the one handling your namespaced code, as the configuration will need to be different:

```php
$classLoader = new ClassLoader('Twig_', __DIR__.'/twig/lib'); // adapt the path to twig
$classLoader->setNamespaceSeparator('_');
$classLoader->register();
``` 

I still suggest using an autoloader implementing standards. and if you use Composer, just use its autoloader, as it is already configured for you automatically.

**Comment by stof** [comment]
Note that the Doctrine ClassLoader is marked as deprecated, so this is another reason not to use it.
