### ISSUE TITLE
PHP 5.4 support broken in Doctrine/Common/Proxy/ProxyGenerator.php on line 62

### ISSUE THREAD

**Issue by jamjamg** [doctrine/common#709]
I get the following error using PHP 5.4.16 and Doctrine Common v2.5.3 under Linux:

<pre>Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in phar:///var/www/html/website.phar/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php on line 62</pre>

The cause seems to be the use of ":class" since this commit:
https://github.com/doctrine/common/commit/3a5d93325b243b0c66405a9f6500ff8ac6fe8464

**Comment by Ocramius** [comment]
`doctrine/common` 2.6.0+ requires PHP 5.5, as per `composer.json` definitions.

**Comment by stloyd** [comment]
Wouldn't be good idea to change those `composer.json` files in existing branches to cover such changes? I.e. https://github.com/doctrine/common/blob/2.5/composer.json#L32 instead of `dev-master` should (IIRC) point to `dev-2.5`.

**Comment by Ocramius** [comment]
branch aliases are only considered in `master`

**Comment by jamjamg** [comment]
oh great, didn't see that 2.6.0+ requires PHP 5.5, so it's not a bug?

**Comment by Ocramius** [comment]
Nope ;-)

**Comment by jamjamg** [comment]
Sorry for the confusion, but i'm using doctrone/common v2.5.3 as my compser.lock tells me. You are saying 2.6.0+ requires PHP 5.5+, so doctrine/common 2.5.3 should work with PHP 5.4?

**Comment by Ocramius** [comment]
@jamjamg did you by mistake run a `composer update` in a >=5.5 environment?

**Comment by jamjamg** [comment]
@Ocramius: indeed: i've got a PHP 5.6 developer machine where I did "composer update", the build server then used compser.lock to package everything up as a phar file...

workarround on a >=PHP-5.5-Machine for this would be:
<pre>COMPOSER_PHP=~5.4 php composer.phar update</pre>

many thanks for your help!

**Comment by tikoflano** [comment]
I think it is even better to use the config value on the composer.json file to specify what PHP version you want to use.

```
{
    "config": {
        "platform": {
            "php": "5.4"
        }
    }
}
```
