### ISSUE TITLE
Umask not configurable anymore

### ISSUE THREAD

**Issue by bcremer** [doctrine/common#710]
Related to: http://www.doctrine-project.org/2015/08/31/security_misconfiguration_vulnerability_in_various_doctrine_projects.html

Since commit https://github.com/doctrine/common/commit/b3ae747e4e63d8785b745762830850160eac2ab4 the `\Doctrine\Common\Proxy\ProxyGenerator` does not respect the global `umask()` anymore.

Unlike `\Doctrine\Common\Cache\FileCache` or `\Doctrine\Common\Annotations\FileCacheReader`, it's lacking a `$umask` parameter in the constructor (See https://gist.github.com/beberlei/dc6e4b018988cba7e211).

Currently there is no way to either widen (`umask(0)`) nor restricting (`umask(0077)`) the permissions of the generated Doctrine ORM proxies.

Would you be open for a pull request that: 
- Adds a new parameter (`$umask = 0002`) to `\Doctrine\Common\Proxy\ProxyGenerator::__construct()`
- Adds a new parameter (`$umask = 0002`) to `\Doctrine\ORM\Proxy\ProxyFactory::__construct()`
- Adds a new configuration option for the umask to `\Doctrine\ORM\Configuration::setUmask()`

**Comment by Majkl578** [comment]
Hello, I'm going to close this issue as we will not be maintaining Doctrine\Common\Proxy anymore. As an alternative, you can use [Ocramius/ProxyManager. ](https://github.com/ocramius/proxymanager). Thank you.
