### ISSUE TITLE
Common\Proxy\Autoloader ClassName problem

### ISSUE THREAD

**Issue by open-it** [doctrine/common#712]
I am having troubles with https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Proxy/Autoloader.php in my project.  (line 52)

My classname is "__CG__MyClassName" and after the str_replace (lien  52) the classname is "_CG__MyClassName" (one _ is missing). If I delete "+1", everything is OK.

Do you have any unit tests that confirm the +1 is needed ?

If not, I suggest to replace :

$className = str_replace('\', '', substr($className, strlen($proxyNamespace) + 1));

by

$className = str_replace('\', '', substr($className, strlen($proxyNamespace)));

**Comment by iluuu1994** [comment]
I'm having the same issue. Are there any news on this issue?

@open-it Were you able to work around the issue somehow?

**Comment by open-it** [comment]
Hello, I've never had any response to this issue. I made my class where I have overriden the method without the +1.

**Comment by Ocramius** [comment]
Did you check https://github.com/doctrine/common/pull/721 ? I think a fix for this was already merged with it.

**Comment by Majkl578** [comment]
This issue has likely been fixed by #721 already, if not please let us know. Also note that Doctrine's Autoloader is deprecated.
