### ISSUE TITLE
ObjectManager could take $object as an argument

### ISSUE THREAD

**Issue by MacDada** [doctrine/common#714]
[`ObjectManager`](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Persistence/ObjectManager.php#L113) currently takes no arguments.

[`EntityManager`](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityManager.php#L353) can take an entity.

I almost always pass the entity I want to persist to avoid side effects. I am forced to typehint `EntityManager`, while I'd like to typehint the `ObjectManager` `interface` (looser coupling).

I guess it is not added so that the implementations can be simpler. Also, adding the `$object` argument to `flush` in `ObjectManager` would probably be a BC–break.

My proposition would be to:

* a.) add `$object` argument to `flush()` in `ObjectManager` (in major version change)
* b.) add `$flushAggregate($object)` method to `ObjectManager` (in major version change)
* c.) add separate `interface` `AggregateFlushingObjectManager` with `$object` argument for `flush()`, that `EntityManager` could implement

That way I could typehint on `ObjectManager` or `AggregateFlushingObjectManager` in my services.

**Comment by Ocramius** [comment]
We are likely going to drop the `flush($entity)` argument further on, as it breaks consistency within a single transaction, and it only led to problems so far.

The problem is in the `EntityManager`, not in the `ObjectManager`.

Also: PHP is perfectly fine with optional parameters defined in subclasses.

**Comment by MacDada** [comment]
> We are likely going to drop the flush($entity) argument further on, as it breaks consistency within a single transaction, and it only led to problems so far.

Oh, I didn't know that and had no problems with that so far.

> The problem is in the EntityManager, not in the ObjectManager

Well, it depends on what u want to typehint on. I'd like to typehint on `ObjectManager` to achieve looser coupling with my code compared to typehinting on `EntityManager`.

> Also: PHP is perfectly fine with optional parameters defined in subclasses.

It's a hack, not a proper solution. Yeah, I could typehint on `ObjectManager` and pass an entity. If the `interface` doesn't say it takes an argument, no implementation is required to do so.

**Comment by Ocramius** [comment]
> It's a hack, not a proper solution.

True, but it is a BC-compliant way to add arguments. Arguably, adding the parameter in first place was a mistake, given that the UoW may be in an inconsistent state when flushing a single entity (missing FK integrity, for example).

You may be interested in https://github.com/doctrine/doctrine2/issues/5550 for this specific sort of API, which is better suited for handling single records.
