### ISSUE TITLE
Make ArrayCollection $_elements protected for extensibility

### ISSUE THREAD

**Issue by redthor** [doctrine/common#730]
Enhancement request.

Could we get `ArrayCollection::$_elements` to be visibility `protected`? `toArray()` will not pass by reference and so we would have to pull all the elements out and then reload them if we want to do something like a `reorder()`.

It would go well with the new Collection enhancement https://github.com/doctrine/mongodb-odm/pull/1385

( See also related https://github.com/doctrine/mongodb-odm/pull/1458 )

Thanks!

**Comment by malarzm** [comment]
Just a small clarification, collection enhancement in question is https://github.com/doctrine/mongodb-odm/pull/1219 as support for sharded collection is for Mongo related stuff

**Comment by Ocramius** [comment]
Please see https://github.com/doctrine/collections/pull/80

**Comment by stof** [comment]
@redthor I don't see anything in https://github.com/doctrine/mongodb-odm/pull/1385 related to doctrine/collection. It is talking about MongoDB collections
