### ISSUE TITLE
Proxies / PHP7 return types: unexpected '\' (T_NS_SEPARATOR)

### ISSUE THREAD

**Issue by bpolaszek** [doctrine/common#736]
Hi there,

It looks like the ProxyGenerator doesn't correctly generate the return type on a namespaced class. Here's my example:

``` php
# src/My/Vendor/Entity/MyEntity.php
namespace My\Vendor\Entity;
class MyEntity {
// ...
    public function getOtherEntity() : OtherEntity {
        return $this->otherEntity;
    }
}
```

And the generated proxy code:

``` php
# var/cache/dev/doctrine/orm/Proxies/__CG__MyVendorEntityMyEntity.php
class MyEntity extends My\Vendor\Entity\MyEntity implements \Doctrine\ORM\Proxy\Proxy {
// ...
    public function getOtherEntity() : \\My\Vendor\Entity\OtherEntity {
        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtherEntity', []);

        return parent::getOtherEntity();

    }
}
```

Which results in the following syntax error:

```
Parse error: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)
```

Indeed a double leading backslash is generated on top of the return type.

Ping #376

**Comment by Majkl578** [comment]
@bpolaszek Strange, which PHP version exactly? Looks like the type already includes backslash. Didn't you experiment with PHP 7.1? If so, there were many reflection changes/breaks in beta/RC, RC3 or newer is required to work properly, especially when combined with nullable types. https://3v4l.org/fItHA
Could you try again with current master? There were some changes regarding PHP 7.1 (see #734).

**Comment by Ocramius** [comment]
Early betas had a `\\` prepended, but newer versions don't prepend it (RC2 and later)

**Comment by ostrolucky** [comment]
seems this is good to close

**Comment by Ocramius** [comment]
Thanks @ostrolucky
