### ISSUE TITLE
ArrayCollection’s ‘matching' : Invalid text representation: 7 ERROR: invalid input syntax for type boolean

### ISSUE THREAD

**Issue by makm** [doctrine/common#742]
ArrayCollection’s ‘matching’ functional is a good feature , but has some problems in use.

When is find entity directly from repository, I have no problem:
            $criteria = Criteria::create()
                    ->andWhere(Criteria::expr()->eq('hidden', ‘false’));
            $categories = $this->categories->matching($criteria);

But if I grep entities from my repository’s class with: 
->addSelect('pc')->leftJoin('p.categories', 'pc')

Doctrine can’t filter by  ‘hidden’ field.

But if I change for:
 ->andWhere(Criteria::expr()->eq('hidden', false));  // boot type

everything fine, but with find entity directly again:

Invalid text representation: 7 ERROR: invalid input syntax for type boolean: ""

**Comment by ostrolucky** [comment]
description of this problem is too obscure, however, doing this in querybuilder
```
->andWhere(Criteria::expr()->eq('hidden', false));
```
is impossible for a long time

**Comment by lcobucci** [comment]
It's indeed hard to understand what's happening here. I'll close it as `Invalid` for now and if @makm is able to provide more info we reopen it.
