### ISSUE TITLE
Error in generated Entity Proxy class

### ISSUE THREAD

**Issue by compains** [doctrine/common#751]
I have started to get errors after updating deployed aplication.

`Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) on /app/cache/prod/doctrine/orm/Proxies/__CG__AppBundleEntityEntityName.php`

Original method

`someMethod( ClassName $inputParam)`
generated proxy

`someMethod ( ? \Full\NamespacePath\ClassName $inputParam)`
I just deleted the ? in the generated code and is working again.

Just to be sure, I re-deployed the app and I got the same issue.

Its running on Php 7.0.8. Deployed version of doctrine common is 2.7.0 (actually this started to happen after update from 2.6.1 to 2.7.0 doctrine/dbal from 2.5.5 to 2.4.5 (don't know why composer has downgraded this package)

**Comment by Majkl578** [comment]
Could not reproduce, can you provide exact code that breaks?

You can modify this snippet (just run `composer require doctrine/common` before executing it):
```php
<?php

require __DIR__ . '/vendor/autoload.php';

class TestClass {
    public function someMethod(DateTime $inputParam) {}
}

$generator = new Doctrine\Common\Proxy\ProxyGenerator(__DIR__, 'Proxy');
$metadata = new class implements Doctrine\Common\Persistence\Mapping\ClassMetadata {
    public function getName() { return TestClass::class; }
    public function getIdentifier() {}
    public function getReflectionClass() { return new ReflectionClass(TestClass::class); }
    public function isIdentifier($fieldName) {}
    public function hasField($fieldName) {}
    public function hasAssociation($fieldName) {}
    public function isSingleValuedAssociation($fieldName) {}
    public function isCollectionValuedAssociation($fieldName) {}
    public function getFieldNames() {}
    public function getIdentifierFieldNames() {}
    public function getAssociationNames() {}
    public function getTypeOfField($fieldName) {}
    public function getAssociationTargetClass($assocName) {}
    public function isAssociationInverseSide($assocName) {}
    public function getAssociationMappedByTargetField($assocName) {}
    public function getIdentifierValues($object) {}
};

$generator->generateProxyClass($metadata, 'TestClass-proxy.php');

require __DIR__ . '/TestClass-proxy.php';
$proxy = new Proxy\__CG__\TestClass;
var_dump($proxy instanceof TestClass);
```

**Comment by compains** [comment]
Not sure where to put this snippet and how to run it. Any tip? please

**Comment by Majkl578** [comment]
Just:
1) create a new folder;
2) create a file, e.g. `test.php`, with this snippet inside;
3) then run `composer require doctrine/common`;
4) and then `php test.php`.
It will create a proxy class for a method with same signature you mentioned in the bug report, but it should create a proxy without any parse errors.
Works for me both under 7.0.11, 7.0.13, 7.1.0 RC6 and 7.1.0 GA.

**Comment by compains** [comment]
I managed to reproduce using this script. 
`<?Php 

require __DIR__ . '/vendor/autoload.php';


class Servicio
{
}

class TestClass {
/**
     * @param Servicio $servicio
     * @param \DateTime $dateTime
     * @return mixed
     */
    public function getTasaAmpliada(Servicio $servicio = null, \DateTime $dateTime)
    {
    }
}

$generator = new Doctrine\Common\Proxy\ProxyGenerator(__DIR__, 'Proxy');
$metadata = new class implements Doctrine\Common\Persistence\Mapping\ClassMetadata {
    public function getName() { return TestClass::class; }
    public function getIdentifier() {}
    public function getReflectionClass() { return new ReflectionClass(TestClass::class); }
    public function isIdentifier($fieldName) {}
    public function hasField($fieldName) {}
    public function hasAssociation($fieldName) {}
    public function isSingleValuedAssociation($fieldName) {}
    public function isCollectionValuedAssociation($fieldName) {}
    public function getFieldNames() {}
    public function getIdentifierFieldNames() {}
    public function getAssociationNames() {}
    public function getTypeOfField($fieldName) {}
    public function getAssociationTargetClass($assocName) {}
    public function isAssociationInverseSide($assocName) {}
    public function getAssociationMappedByTargetField($assocName) {}
    public function getIdentifierValues($object) {}
};

$generator->generateProxyClass($metadata, 'TestClass-proxy.php');

require __DIR__ . '/TestClass-proxy.php';
$proxy = new Proxy\__CG__\TestClass;
var_dump($proxy instanceof TestClass);
`

when i run

`php test.php`

I get the same error:

`PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/ubuntu/test/TestClass-proxy.php on line 179`

**Comment by Ocramius** [comment]
Argh, we didn't consider this scenario. The first parameter is nullable,
but not optional (due to second parameter). This is a fuckup on both sides,
since the code is bogous, yet valid.

**Comment by compains** [comment]
This means that a signature like 

`public function getTasaAmpliada(Servicio $servicio = null, \DateTime $dateTime=null)`

should work?

**Comment by compains** [comment]
Changing signature works. 

This is considered a bug and will be fixed or I should take care of doing proper function signatures?

**Comment by Ocramius** [comment]
@compains this is a valid bug, and needs fixing.

**Comment by Majkl578** [comment]
Changing `isOptional()` to `isDefaultValueAvailable()` inside `ProxyGenerator::formatType()` should do the trick I believe. @Ocramius should I send a PR or are working it already? :)

---

And it doesn't even generate a warning... 😢
![becausephp](https://cloud.githubusercontent.com/assets/144181/20847621/3e7a2250-b8cf-11e6-8087-5ac0c08fa79e.jpeg)

**Comment by Ocramius** [comment]
@Majkl578 I'm currently working on a patch: should take few minutes.

**Comment by Ocramius** [comment]
@Majkl578 @compains can you check #752 please?

**Comment by compains** [comment]
Tested in same machine and working. Thanks!!! Great job.

**Comment by Majkl578** [comment]
@compains Either way, I'd suggest to avoid such code, personally I'd be 💯 for a warning in php-next, because such code is extremely fragile... 💣

**Comment by compains** [comment]
@Majkl578 I totally agree with you, an warning would be really helpful. In any case I have already refactored that signatures.
