### ISSUE TITLE
Incompatible with doctrine/orm

### ISSUE THREAD

**Issue by fmonts** [doctrine/common#755]
Can't use doctrine/common 2.7.x with doctrine orm:

`doctrine/orm v2.5.5 requires doctrine/common >=2.5-dev,<2.7-dev -> satisfiable by doctrine/common[2.5.x-dev, 2.6.x-dev, v2.5.0, v2.5.0-beta1, v2.5.1, v2.5.2, v2.5.3, v2.6.0, v2.6.1, v2.6.2] but these conflict with your requirements or minimum-stability.`

**Comment by Majkl578** [comment]
Wait for doctrine/orm 2.5.6 or temporarily require `doctrine/common 2.7.1 as 2.6.99`, see doctrine/doctrine2#6156.

**Comment by fmonts** [comment]
`"doctrine/common": "2.7.1 as 2.6.99"` worked. Thank you
