### ISSUE TITLE
Inflector pluralize "page child" -> "page phildren"

### ISSUE THREAD

**Issue by laszlokorte** [doctrine/common#758]
I am using the inflector to display db table names pluralized to the user. Eg I have a table `committee_member` and I wand to display it in the UI's navigation as "Comment members".

I am not sure if the pluralization is expected to support composed words like `committee member` or `page child` but the following does not yield the correct result:

```
$inflector = new Doctrine\Common\Inflector\Inflector();
$inflector->pluralize("page child");
// Expected: page children
// Actual: page phildren
```

(the first letter of the second word is replaced by the first letter of the first word)

**Comment by Ocramius** [comment]
@laszlokorte only single words are supposed to be pluralized, sorry.

**Comment by laszlokorte** [comment]
@Ocramius What about hyphenations `super-child`? Here the same issue occurs.

I am not a native speaker so I am not 100% sure what counts as one word. In german we can compose words without spaces: `fruit`+`fly` = `fruit fly` ... `Frucht`+`Fliege`=`Fruchtfliege`

**Comment by Ocramius** [comment]
@laszlokorte same stuff - was never designed to handle more than one word.

Any non-alphabetic character in an English sentence delimits two completely separate words. If there are exceptions to this rule, this library can't really deal with those.

**Comment by laszlokorte** [comment]
Ok, thanks
