### ISSUE TITLE
Void return type on proxies fails

### ISSUE THREAD

**Issue by Garbee** [doctrine/common#759]
If I setup a model that has a `: void` return type hint on a setter, this causes a failure with the generated proxy. As the void return type hint is added to the proxy, but the proxies always *return* the call to the main class.

I recommend that if a void return type is present, `return` is not inserted into the generated proxy (to avoid these compile-time errors.) Or, if the proxies must return something for internal purposes, they detect the void return type and strip it from the proxy class.

<details>
<summary>Example class</summary>

```php
<?php

class Product
{
  private $name;

  public function __construct(string $name)
  {
    $this->id = uuid4();
    $this->name = $name;
  }

  public function getName() : string
  {
    return $this->name;
  }

  public function setName(string $name) : void
  {
    $this->name = $name;
  }
}
```

</details>

**Comment by Ocramius** [comment]
Please ensure that you have doctrine/common 2.7.*

**Comment by Garbee** [comment]
Ah yea, I see support for this was added in commit 87dc24e552708ede4d3edd58ff07e6e93f94822a. I'm using `laravel-doctrine/fluent` which is requiring the `2.5` branch explicitly. I'll try to force it locally and ask the maintainers of that to update if I can't bypass their requirement.

Thanks @Ocramius.

**Comment by Ocramius** [comment]
This also needs a DBAL release btw: didn't manage to preparare it during
the xmas holidays, sadly

**Comment by Garbee** [comment]
Personally I'm not sure if I'm even hitting much of the DBAL stuff at this point. I manually do my migrations and all using another system. I just spent like 6 hours the other day debugging weird errors that turned out to be this void return type problem.

**Comment by Garbee** [comment]
So, adding `doctrine/common: ~2.7` to the requirements and setting `minimum-stability: dev` got it to install. Testing with that after generating the proxies everything is working out.

Thank you!
