### ISSUE TITLE
empty() and boolean cast on empty ArrayCollection

### ISSUE THREAD

**Issue by fmonts** [doctrine/common#764]
I think this behavior is not consistent and not as one would expect:

$coll = Array();
var_dump((bool)$coll); // FALSE
var_dump(empty($coll)); // TRUE

$coll = new ArrayCollection();
var_dump((bool)$coll); // TRUE
var_dump(empty($coll)); // FALSE

**Comment by stof** [comment]
PHP does not allow to control the boolean casting of objects or the behavior of ``empty``. So there is strictly nothing we can do
