### ISSUE TITLE
ProxyFactory may generate invalid proxies with no error

### ISSUE THREAD

**Issue by theofidry** [doctrine/common#770]
Follow up of https://github.com/symfony/symfony/issues/21509

If for example the entity is final, as the generated proxy make use of inheritance, this throw a `FatalError` when the proxy class is being used. However, this error is thrown at runtime when the proxy is being used, not when it is generated. WDYT of adding a simple `include_once` on the generated proxy when creating it, to throw an error as early as possible?

**Comment by Ocramius** [comment]
Would rather just throw an exception in the generator, before writing any
code or generating anything

**Comment by theofidry** [comment]
The only case I've ever encountered the issue is when dealing with `final` classes, but I don't know and I suspect there is other cases as well where including the file ensures the generated PHP code is valid.

That said I'm fine with just doing a PR for the final case.

**Comment by Ocramius** [comment]
Fixed via #771
