### ISSUE TITLE
Error in ProxyGenerator

### ISSUE THREAD

**Issue by dylanz** [doctrine/common#774]
On PHP 5.4.45-4, I'm running into the following:
```
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php on line 62"
```

The code in question is when it's trying to evaluate Proxy::class here:
```
protected $placeholders = [
        'baseProxyInterface'   => Proxy::class,
        'additionalProperties' => '',
    ];
```
Any ideas on why this would crop up?

**Comment by Majkl578** [comment]
Sorry, but PHP 5.6 or newer is required.

**Comment by dylanz** [comment]
@Majkl578 Ah, that makes sense.  Thanks for the quick reply!
