### ISSUE TITLE
Issue Tracker (JIRA) seems to be down

### ISSUE THREAD

**Issue by fridde** [doctrine/common#779]
Ironically, I'd like to make a bug report about the inability to report bugs.

Can someone check out why http://www.doctrine-project.org/jira gives a **404 - Not found** ?

**Comment by Ocramius** [comment]
Jira has been put to eternal sleep over a year ago: just report issues here, please :-)

**Comment by stof** [comment]
@Ocramius the readme still links to JIRA

**Comment by Ocramius** [comment]
@stof urgh... @fridde can you send a patch to correct that?
