### ISSUE TITLE
Priority in EventManager

### ISSUE THREAD

**Issue by chapterjason** [doctrine/common#782]
Hi, an Priority option in the [Doctrine/Common/EventManager](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/EventManager.php) would be awesome. I have a little scenario where it depends on the ordner of events.

I've got two `PreUpdate` events, the first modify a field, and the second one takes the fields and create a `HistoryEntry`. the order here is really important, cause of the wrong data that would be applied to the `HistoryEntry` cause the first event does't modified the necessary field.

I also refer to an issue on [symfony](https://github.com/symfony/symfony/issues/21977) that was declined because of the doctrine implementation.

**Comment by Ocramius** [comment]
@chapterjason the doctrine EventManager implementation is supposed to be tiny/lightweight. Having priorities would change the interface and also make it much slower (not by much, but I expect 0.5 times the current throughput).

Why not just use something like https://github.com/zendframework/zend-eventmanager, which has these features, and has already been heavily optimized?
