### ISSUE TITLE
STARTS_WITH missing from BasicEntityPersister when using criteria ExpressionBuilder

### ISSUE THREAD

**Issue by MartinLyne** [doctrine/common#783]
Trying to use a criteria with "startsWith" like so 

` $criteria->andWhere($criteria->expr()->startsWith('column', 'startString'));`
which gives me `Invalid index STARTS_WITH` in `/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php`

Here's my doctrine `composer list -i`

```
doctrine/annotations                   v1.4.0             Docblock Annotations Parser
doctrine/cache                         v1.6.1             Caching library offering an object-oriented API for many cache backends
doctrine/collections                   v1.4.0             Collections Abstraction library
doctrine/common                        v2.7.2             Common Library for Doctrine projects
doctrine/dbal                          v2.5.12            Database Abstraction Layer
doctrine/doctrine-bundle               1.6.7              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle         1.3.0              Symfony Bundle for Doctrine Cache
doctrine/inflector                     v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                  1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                         v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                           v2.5.6             Object-Relational-Mapper for PHP
```
`

I checked the file and it only has Comparison mappings for the usual suspects. Is this a composer version issue?

Thanks

**Comment by Majkl578** [comment]
This should be reported against doctrine/doctrine2 repository (or doctrine/collections), not here.

STARTS_WITH and ENDS_WITH is not supported by Doctrine ORM (yet), see doctrine/doctrine2#6397. It was added to doctrine/collections just recently, in 1.4.0 version, see https://github.com/doctrine/collections/pull/78.

**Comment by lcobucci** [comment]
@MartinLyne as @Majkl578 this is a new feature in ORM and will land in `v2.6` only (I've just merged it).

Closing as `invalid` since it's not a `doctrine/common` issue.
