### ISSUE TITLE
Possible bug when generating methods with return types

### ISSUE THREAD

**Issue by adri** [doctrine/common#784]
When using return types for an identifier getter I got executed queries when calling `$entity->getId()`. I tracked it down to the ProxyGenerator.

With the return type:

```php
    public function getId() : ?int
    {
        return $this->id;
    }
```
Generates: 
```php
/**
 * {@inheritDoc}
 */
public function getId(): ?int
{

    $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

    return parent::getId();
}
```

Without the return type:
```php 
    public function getId() 
    {
        return $this->id;
    }
```

Generates:

```php
/**
 * {@inheritDoc}
 */
public function getId(): ?int
{
    if ($this->__isInitialized__ === false) {
        return (int)  parent::getId();
    }

    $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

    return parent::getId();
}
```

Seems like changing [this regex](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Proxy/ProxyGenerator.php#L40) to the following fixes this issue:

```php
    const PATTERN_MATCH_ID_METHOD = '((public\s+)?(function\s+%s\s*\(\)\s*)\s*(?::\s*\\\\?[\?a-z_\x7f-\xff][\w\x7f-\xff]*(?:\\\\[a-z_\x7f-\xff][\w\x7f-\xff]*)*\s*)?{\s*return\s*\$this->%s;\s*})i';
```

Any hints where this method is tested? I can't seem to find it (to make a PR).

**Comment by Ocramius** [comment]
See https://github.com/doctrine/common/blob/5bd8542e485bb60d137ee4895c4e70c3925f603a/tests/Doctrine/Tests/Common/Proxy/ProxyLogicIdentifierGetterTest.php

**Comment by adri** [comment]
This was fixed already in https://github.com/doctrine/common/commit/ef455c443c4554883ff9fb04c6293dabe8ec7971 :)
