### ISSUE TITLE
Add getRepositoryClass method to ClassMetadata interface

### ISSUE THREAD

**Issue by szymach** [doctrine/common#786]
Hello, 
I have recently ran into a situation, where knowing the entity's repository class name was required and I could either:

1. Instantiate the repository through the registry or object manager and perform a `get_class()` call (if I wanted to stick to `doctrine/common` interface).
2. Use the `customRepositoryClassName` field in in ORM\ODM `ClassMetadataInfo` classes.

As far as I can tell, repositories are things that are present regardless of implementation (ORM or ODM) and it would be nice to get a clean (as in supported by a common interface) method of retrieving any entity / document repository class name.

The only reason I ask is that this can be bothersome to do if you are maintaining a bundle that relies on Doctrine, but not on specific implementation and cannot simply assume you get a class that will provide this field as a public one. Let me know if this is something worth considering and thanks in advance for an answer.

**Comment by Ocramius** [comment]
Adding methods to an interface is not possible due to BC constraints. We can revisit this when moving ORM v3 interfaces into the package though.

**Comment by szymach** [comment]
Cool, so do I close this issue or would you like it to be left open until you start revisiting the interfaces?

**Comment by Ocramius** [comment]
@szymach probably better to close and jump in during the alpha stages?

**Comment by szymach** [comment]
Alright, closing then. Thanks for the feedback :)
