### ISSUE TITLE
ProxyGenerator ignores public embedded fields

### ISSUE THREAD

**Issue by mkosiedowski** [doctrine/common#787]
Getting public embeddables on lazy-loaded entity which is not initialized does not trigger entity initialization.

Bug is in `\Doctrine\Common\Proxy\ProxyGenerator::getLazyLoadedPublicProperties` in code:
```php
if (($class->hasField($name) || $class->hasAssociation($name)) && ! $class->isIdentifier($name)) {
    $properties[$name] = $defaultProperties[$name];
}
```
This code only checks for fields and associations, but not for embeddables. For now the interface `\Doctrine\Common\Persistence\Mapping\ClassMetadata` doesn't even provide any function to check if a field is an embeddable object.

**Comment by mkosiedowski** [comment]
As agreed in https://github.com/doctrine/common/pull/788 this should be fixed in ORM

**Comment by Ocramius** [comment]
Handled in https://github.com/doctrine/doctrine2/pull/6462
