### ISSUE TITLE
"requires" problem with php version

### ISSUE THREAD

**Issue by raketman** [doctrine/common#797]
We use your bundle in our projects. Today we updated project with composer update and got problem with php version.

For example doctrine/common requires "doctrine/cache: 1.*"
New release of doctrine/cache "dev-master / 1.7.x-dev 2017-05-20 19:47 UTC" require php: ~7.1.

And now any doctrine/common > 2.4 requires php 7.1 after update.

Can you change major of  "dev-master / 1.7.x-dev 2017-05-20 19:47 UTC"?

**Comment by alcaeus** [comment]
First of all, `dev-master` of doctrine/cache is only eligible if either:
* you yourself require `dev-master` in your composer.json
* you specify `minimum-stability: dev` in your composer.json

Furthermore, if you're not running `composer update` on PHP 7.1, `dev-master` simply isn't eligible, so composer won't consider it and will install a version suitable for your PHP version.

This is nothing we can or will fix - the development version will not be pulled in unless you ask it to, and composer will guard against using a version of doctrine/cache that doesn't support your PHP version. Closing as invalid.
