### ISSUE TITLE
PHP Minimums Mismatch

### ISSUE THREAD

**Issue by robertdown** [doctrine/common#799]
`doctrine/common` version 2.5.0 requires PHP >= 5.3.2 however downstream the `doctrine/annotations` requirement now sets the minimum PHP value to ^5.6.

This appears to happen because in the `common` composer file it sets the requirements for `annotations` to `1.*`. The last version of `annotations` to support `PHP >=5.3.2` is `1.2.7`

**Comment by Ocramius** [comment]
@robertdown make sure you run `composer update` on a system that is alike your production environment. Also, you can enforce platform constraints at the root of your project, in `composer.json`, via something like following:

```json
{
    "config": {
        "platform": {
            "php": "5.4.45"
        }
    }
}
```

Closing as `invalid`.

**Comment by robertdown** [comment]
Been working with composer for many years now and never ran into this issue before. Your suggestion worked, thanks. Sorry to open an errant issue.
