### ISSUE TITLE
Dependency Issues mismatch required PHP version

### ISSUE THREAD

**Issue by GavinCS** [doctrine/common#810]
doctrine/common v2.6.0 supports php > 5.5, however it depends on packages which no longer support php 5.5,5.6

Example: the requirement for doctrine/annotations is 1.*, therefore it installs the latest release 1.5.0, which no longer supports php5.

Please fix

**Comment by alcaeus** [comment]
See http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html. Closing as `invalid`.
