### ISSUE TITLE
ProxyGenerator::formatType() not Trait friendly

### ISSUE THREAD

**Issue by dohpaz42** [doctrine/common#811]
I have a Trait that I would like to use on multiple entities. As part of my coding style, I like to return `$this` to make my objects chainable. I've recently upgraded to PHP 7.1, and I've started implementing return types. Because my setters in my Trait have no knowledge of who uses them, and also because PHP can only return one type, I use the Trait name as the return type. 

The problem is, in ProxyGenerator::formatType(), it is only testing for `class_exists()` and `interface_exists()`, and not including `trait_exists()`, as it does in `ClassLoader::typeExists()`. Because of this, the following exception gets thrown:

```
  [Doctrine\Common\Proxy\Exception\UnexpectedValueException]
  The return type of method "myMethod" in class "Path\To\My\ConcreteClass" is invalid.


Exception trace:
 () at /var/www/vendor/doctrine/common/lib/Doctrine/Common/Proxy/Exception/UnexpectedValueException.php:78
 Doctrine\Common\Proxy\Exception\UnexpectedValueException::invalidReturnTypeHint() at /var/www/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php:1077
 Doctrine\Common\Proxy\ProxyGenerator->formatType() at /var/www/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php:1026
 Doctrine\Common\Proxy\ProxyGenerator->getMethodReturnType() at /var/www/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php:781
 Doctrine\Common\Proxy\ProxyGenerator->generateMethods() at n/a:n/a
 call_user_func() at /var/www/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php:276
 Doctrine\Common\Proxy\ProxyGenerator->generateProxyClass() at /var/www/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:155
 Doctrine\Common\Proxy\AbstractProxyFactory->generateProxyClasses() at /var/www/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php:71
 Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp() at /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:499
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:116
 Symfony\Component\HttpKernel\Kernel->boot() at /var/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:134
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /var/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:96
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:854
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:201
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:125
 Symfony\Component\Console\Application->run() at /var/www/bin/console:23
```

I would be more than happy to help write a PR for this, but I wanted to ask first about my potential strategy:

Since `ClassLoader::typeExists()` already implements the logic we're looking for in `ProxyGenerator::formatType()`, I think it would make sense to move `ClassLoader::typeExists()` into `ClassUtils`, and then add `ClassUtils` to `ClassLoader` and update the three usages.

This would then allow us to re-use that same logic in `ProxyGenerator::formatType()`, and then if any future `*_exists()` comes up (or whatever), there would only be the one place to maintain it.

For what it's worth, I yield to your experience, and if you feel that is overkill, I can easily add the `trait_exists()` call into `ProxyGenerator::formatType()` and be done with it. 

Thank you.

**Comment by Majkl578** [comment]
Traits are not types, they can't be relied upon nor typehinted upon. Any attempt to typehint trait will result in an error. See https://3v4l.org/cGaNW and php.net/traits.
If you need return types in traits returning `$this`, you can try `self` which will be dynamically resolved to the class where the trait is used, see https://3v4l.org/aWJIi.

**Comment by dohpaz42** [comment]
@Majkl578, wow! I like your idea better! It never occurred to me to go look at the [type hint documentation](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) (I blame the late hour, and newness to 7.1). 

Seriously, thank you; you've made my day!
