### ISSUE TITLE
"Starts With" comparison doesn't work with Doctrine ORM

### ISSUE THREAD

**Issue by blowski** [doctrine/common#818]
I'm trying to search for "Wherever name starts with x", so I've created a criteria and added the following:

`$criteria->andWhere(Criteria::expr()->startsWith('name', 'x'));`

However, the ORM throws an exception in `vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php (line 1611)`

Notice: Undefined index: STARTS_WITH

If I change to use a `contains` expression, then it works as expected.

**Comment by Majkl578** [comment]
STARTS_WITH and ENDS_WITH is not yet supported by stable version of Doctrine ORM, doctrine/doctrine2#6397 is only merged into master and will be available in 2.6.

Closing here, not an issue of doctrine/common.
