### ISSUE TITLE
flush() prototype in interface differs from implementation

### ISSUE THREAD

**Issue by dstensnes** [doctrine/common#821]
[interface](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Persistence/ObjectManager.php#L120) says 
`public function flush();`
but [implementation](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityManager.php#L354) says
`public function flush($entity = null)`
This makes our phpstan complain when we try to flush a specific entity:
`Method Doctrine\Common\Persistence\ObjectManager::flush() invoked with 1 parameter, 0 required.`
Update interface to match?

**Comment by Ocramius** [comment]
That's gonna be fixed only in develop. Also, implementations can define
additional optional parameters in PHP: this has always been a life-saver
for BC compliance policy restrictions.

**Comment by dstensnes** [comment]
Didn't know. Thanks :)

**Comment by Majkl578** [comment]
Closing, ORM will no longer support single entity flush as of version 3.0.
