### ISSUE TITLE
validate for column/table names not being reserved keywords

### ISSUE THREAD

**Issue by FyiurAmron** [doctrine/common#825]
FWIW, there's a lot of StackOverflow/GitHub issues about people who used one of many SQL's reserved keywords in their ORMs:

https://stackoverflow.com/questions/20798240/doctrine2-sqlstate42000-syntax-error-or-access-violation-1064
https://stackoverflow.com/questions/35154203/sqlstate42000-syntax-error-or-access-violation-1064-symfony-2-7-3-applicatio
https://stackoverflow.com/questions/23446377/syntax-error-due-to-using-a-reserved-word-as-a-table-or-column-name-in-mysql
https://stackoverflow.com/questions/19147073/why-sqlstate42000-syntax-error-or-access-violation
https://stackoverflow.com/questions/14437031/syntax-error-on-a-doctrine-query-symfony2
https://github.com/doctrine/common/issues/165
https://github.com/doctrine/doctrine2/issues/3281
https://github.com/nextcloud/server/issues/3140
etc. etc.

The list of SQL's reserved words https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words is _quite extensive_, and some are extremely obscure. I've already hit three of those *by accident* in *two days*. The simplest solution IMO would be for Doctrine to actually make column/table names that are colliding with SQL's RW's simply fail validation. `doctrine:schema:validate`, "column name can't be an SQL reserved keyword; either change or quote with backticks" reported, et voila, instead of the ugly and cryptic "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax".

**Comment by Majkl578** [comment]
Please refer to the ORM documentation in the Limitations section: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases

Since this is not related to Common, I'll close this issue, please open new one in appropriate repository if you still think it's a problem that needs addressing.

**Comment by FyiurAmron** [comment]
@Majkl578 I am well aware of the Limitations. I never said I consider force-quoting them an option. Do you perhaps know _what specific component_ (or at least repo location) handles the validation in the Symfony-Doctrine tandem? I was under the assumption that Doctrine does most of the validation on its own...

**Comment by Majkl578** [comment]
That would be [the ORM itself](https://github.com/doctrine/doctrine2).
