### ISSUE TITLE
Doctrine\Common\Lexer should be marked as deprecated

### ISSUE THREAD

**Issue by stof** [doctrine/common#846]
The logic was moved to doctrine/lexer in 2013 and this class kept as a BC layer (extending the abstract class from the lexer component).

This class should be marked as deprecated in a 2.x release to ensure everyone has migrated to the new component.

**Comment by stof** [comment]
The same is true for `Doctrine\Common\Util\Inflector` btw

**Comment by Majkl578** [comment]
This is already part of #845, please review there. :+1:

**Comment by Majkl578** [comment]
Handled via #845.
