### ISSUE TITLE
Error: Field with default value cannot be null 

### ISSUE THREAD

**Issue by BernardA** [doctrine/common#847]
The following error will be thrown when attempting to make an insert on the table

> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'is_active' cannot be null

Normally this should not cause an issue. The field has a default value set as follows:

         /**
         * @ORM\Column(type="boolean", options={"default":false})
         */
        private $isActive;

The database table corresponds to the above config, ie:
type: tynyint(1)
null: no
default: 0

This is on Symfony 4, mysql.

Thanks

**Comment by Ocramius** [comment]
This is normal:  Doctrine ORM will always use the in-memory state to decide what to bind to an `INSERT` SQL statement, and it is your responsibility to keep the state of the object consistent with the invariants that you set. The ORM just loads/saves whatever it finds without asking many questions, as it should.

**Comment by BernardA** [comment]
@Ocramius Well, not sure i agree with your statement, terse language and all. What good is to have annotations that are virtually useless? If they are good for nothing, as it seems, you should avoid given people the illusion that it will serve some purpose. 
If I have to verify it myself, I would just as well skip the annotation completely.

**Comment by jwage** [comment]
The options array and default value is for the schema creation in the database, not for providing a default value when flushing. Add a default value of false to the property in your class and you shouldn't get an error anymore.

**Comment by camohub** [comment]
But as I define default value on database layer I expect that Doctrine will respect it and suppose this property as optional.

**Comment by Ocramius** [comment]
@camohub no, the default value is something that changes post-persistence, and the ORM will not re-fetch records to check their value afterwards.

You have two possibilities there:

 1. explicitly call `EntityManager#refresh()` on a newly persisted entity, to force a re-fetch
 2. avoiding post-insert state mutation (default values, state-mutating triggers)

Locking here, as the topic is a long-standing invariant of the ORM that will not change in the near future.
