### ISSUE TITLE
Bug: Proxy: Support of PHP 7 return type hints in magic method

### ISSUE THREAD

**Issue by janbarasek** [doctrine/common#868]
Hello,

I am using version `v2.10.0` with PHP `7.2.14`.

In entities I use trait `SmartObject` (https://doc.nette.org/en/2.4/smartobject) implements magic methods (for example `__isset()`) with scalar type hints.

I know new version of `ProxyGenerator` make proxy methods with type hints, but in magic methods not.

On runtime I get a PHP error: `Declaration of ShopUp\Database\Proxy\__CG__\ShopUp\UserAdvance\Entity\AdvanceUser::__isset($name) must be compatible with ShopUp\Security\Entity\User::__isset(string $name): bool`

Generated proxy class:

<img width="746" alt="Snímek obrazovky 2019-04-08 v 10 27 39" src="https://user-images.githubusercontent.com/4738758/55709584-f0dfe300-59e8-11e9-9795-acfd026484b9.png">

But in real entity is:

<img width="661" alt="Snímek obrazovky 2019-04-08 v 10 28 08" src="https://user-images.githubusercontent.com/4738758/55709611-01905900-59e9-11e9-9072-c056bca76a00.png">

Thank you for support.

**Comment by janbarasek** [comment]
Please merge my changes and create new version: https://github.com/doctrine/common/pull/869

**Comment by rybajz** [comment]
Hi,
I have the same problem. Is there any progress? Can you merge @janbarasek suggest?

Thanks

**Comment by janbarasek** [comment]
@rybajz I understand your trouble but I I could not make a correction that meets all the requirements.

Typical case when is problem is `SmartObject` trait in Nette Framework: https://doc.nette.org/en/3.0/smartobject

**Comment by platx** [comment]
Any updates? I got the same issue with some external lib, that couldn't be changed by me, but i should use proxy functional for this lib.

**Comment by malarzm** [comment]
It seems like https://github.com/doctrine/common/pull/869 still has some not addressed comments. Do you want to pick it up and finish?

**Comment by janbarasek** [comment]
Finally done! And we're going to celebrate! :)

**Comment by rybajz** [comment]
Great!
