### ISSUE TITLE
PHP 7.4 Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by esbobkov** [doctrine/common#872]
We have 
https://github.com/doctrine/common/blob/6bc33d1f26fb8653cda552e8e69f15d1e8512ade/lib/Doctrine/Common/Proxy/ProxyGenerator.php#L1024

Is it safe change it to `$name = $type->getName();`?

**Comment by Ocramius** [comment]
Kinda: need to consider nullability too

**Comment by savandholu** [comment]
**Change1:**

File: vendor/zendframework/zend-code/src/Reflection/ParameterReflection.php
In function `detectType()` replace line

`return (string) $type;
`
with
`return $type->getName();
`

**Change2:**

Error: Deprecated Functionality: implode(): Passing glue string after array is deprecated
File: vendor/magento/framework/DB/Sql/UnionExpression.php
In function `__toString()` replace line

`$sql = implode($parts, $this->type);
`
with
`$sql = implode($this->type,$parts);
`

**Change3:**

File: vendor/magento/framework/App/AreaList.php
In function `getCodeByFrontName()` replace line

`if ($areaInfo['frontName'] == $frontName)
`
with
`if (isset($areaInfo) && $areaInfo['frontName'] == $frontName)`


Hope it helps you,
Thanks In Advance

**Comment by stof** [comment]
@savan13 none of these code snippets are in doctrine/common.
