### ISSUE TITLE
Public typed class properties incompatible with lazy fetch mode in PHP 7.4

### ISSUE THREAD

**Issue by a-menshchikov** [doctrine/common#881]
There is a Notice from \Doctrine\Common\Proxy\ProxyGenerator::getLazyLoadedPublicProperties about undefined index when I use public typed properties in my class without any default value.

**Comment by Niko9911** [comment]
I was just doing issue and patch for this. Thank you for doing this before me. This allows me doing quick hotfix and continue work. :)

Please merge it ASAP.

**Comment by Ocramius** [comment]
Marked both as bug and as new feature: it won't land in a patch release, but it will land in the next minor
