### ISSUE TITLE
Bugs: AbstractProxy::getProxyDefintion AUTOGENERATE_NEVER

### ISSUE THREAD

**Issue by EliuFlorez** [doctrine/common#885]
![error-1](https://user-images.githubusercontent.com/784787/76129732-01b02480-5fbd-11ea-9e8a-461520953244.png)

**Comment by alcaeus** [comment]
You need to generate proxies manually using a command when using the “never” autogenerate strategy.

In the Future, please try to include more information in a support question instead of just posting a screenshot. Thanks!
