### ISSUE TITLE
Proxy generating __sleep with uninitialized properties (PHP7.4.2+)

### ISSUE THREAD

**Issue by bizley** [doctrine/common#886]
Proxy generator is creating `__sleep` method with uninitialized typed properties which is a critical bug since PHP 7.4.2 (https://bugs.php.net/bug.php?id=79002) ending in message:

> Typed property Proxies_CG_\App\Entity\EntityName::$ must not be accessed before initialization (in __sleep)

I've already reported it (not knowing the source of error hence the wrong repo) in https://github.com/doctrine/orm/issues/8030 but it looks like it's stuck there forgotten.

**Comment by 2ec0b4** [comment]
I'm stuck with the same error. I manage to reproduce it with the smallest Symfony project. Here it is: https://github.com/2ec0b4/symfony-proxy-issue

**Comment by sebastianlew** [comment]
I wanted to make PR fixing that problem, but i think it isn't as simple as we think :)

Few ideas that i had:

1. Maybe better solution is to serialize just identifier if entity is not initialized yet. But what with case when we serialize uninitialized entity, and then try to unserialize and access some property? Same problem, we get an error that property is not initialized.

2. And in my opinion, the best solution is to initialize whole entity in _sleep before we serialize it. But again, what about performance in this case

**Comment by nicolas-grekas** [comment]
To me, a fix should be considered at the PHP level, I opened https://bugs.php.net/79447 :crossed_fingers:

**Comment by sebastianlew** [comment]
@nicolas-grekas That’s why I wrote 

> I wanted to make PR fixing that problem, but i think it isn't as simple as we think :)

cause i didn’t see any perfect solution to solve this problem directly in doctrine 😁

**Comment by nicolas-grekas** [comment]
https://github.com/php/php-src/pull/5396 will be part of PHP 7.4.6, this nothing to do here.

**Comment by sebastianlew** [comment]
@nicolas-grekas I saw that problem escalated a little and also your PR was closed on php src. Will that problem be fixed soon in php src? What's the state of this problem for now ?

**Comment by nicolas-grekas** [comment]
Give PHP 7.4.6 a try, it's been released yesterday.

**Comment by sebastianlew** [comment]
Everything works fine now 🎉  , thank you @nicolas-grekas

**Comment by Ocramius** [comment]
Probably best to add an exclusion range for `7.4.0~7.4.5`

**Comment by alcaeus** [comment]
> Probably best to add an exclusion range for `7.4.0~7.4.5`

That won't help: any release without this exclusion is still eligible but also suffers from the problem. This is not our problem to fix.

**Comment by Ocramius** [comment]
It would still make upgrading to latest version clear and blocked off until 7.4.6 is installed (good).

This has been done for similar reasons in:

 * https://github.com/Ocramius/ProxyManager/releases/tag/2.7.1
 * https://github.com/Ocramius/ProxyManager/releases/tag/2.8.0

Overall, it provides guidance for downstream, and this package is indeed still broken in 7.4.0~7.4.5.

**Comment by sebastianlew** [comment]
I think that first step also could be improvement of the tests in doctrine/common cause despite this problem tests have been passing for e.g. `tests/Doctrine/Tests/Common/Proxy/LazyLoadableObjectWithTypedProperties.php` (I'll try to do it if nobody do it first)

**Comment by beberlei** [comment]
Closing as its a PHP bug.
