### ISSUE TITLE
Compatibility with doctrine/inflector:2.0

### ISSUE THREAD

**Issue by W0rma** [doctrine/common#889]
`doctrine/orm` 2.x relies on `doctrine/common` which does only allow installation of `doctrine/inflector:^1.0`.

After the release of `doctrine/inflector:1.4` this leads to deprecation notices in `doctrine/orm`:

`The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.`

I guess this package should support both 1.0 and 2.0 at the same time? In this case this package may need some BC layer similar to https://github.com/symfony/maker-bundle/pull/600

**Comment by alcaeus** [comment]
The deprecation notice can be fixed by migrating to the new API, which is available in inflector 1.4 as well. This package will not be updated to accept inflector 2.0, as this is in the process of being phased out.

**Comment by W0rma** [comment]
Thanks for your quick reply.

This means `doctrine/orm` 2.7/2.8 must be migrated to the new API. However, it is not possible to install inflector 2.0 as long as `doctrine/common` is a dependency there (the dependency has already been removed in [master](https://github.com/doctrine/orm/pull/7497) but not in 2.7/2.8 which are still maintained).

**Comment by alcaeus** [comment]
> This means doctrine/orm 2.7/2.8 must be migrated to the new API.

That is correct. Note that updating to the new API does not require installing Inflector 2.0. Once migrated to the new API, no deprecation notices will be emitted.
