### ISSUE TITLE
Notice: Undefined variable: name in generated Proxy class

### ISSUE THREAD

**Issue by flack** [doctrine/common#896]
Since upgrading to 3.0.1, I get the following notice:

```
Notice: Undefined variable: name in [generated proxy class] on line 75
```

The generated code looks like this:

```php
    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($field, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }
```

in version 3.0.0 it looked like this:

```php
    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
    }
```

Either all occurences of `$name` should be replace by `$fieldd` or none of them

**Comment by greg0ire** [comment]
If I had to make a bet I'd say this is related to 0f00cb90562ae434b3b2c62db9568bf945cca5a9

**Comment by greg0ire** [comment]
@janbarasek  @miloshavlicek can you please have a look at this?

**Comment by flack** [comment]
`__isset` has the same problem btw:

```php
    /**
     * {@inheritDoc}
     * @param  string $name
     * @return boolean
     */
    public function __isset($field)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

        return parent::__isset($name);
    }
```

**Comment by miloshavlicek** [comment]
I'll fix it ASAP. I am sorry for that.

**Comment by greg0ire** [comment]
Thanks a lot :pray:

**Comment by obstschale** [comment]
I reported the same Issue in #898 but we use v2.7.3. Are you going to fix it for v2.x as well?

**Comment by greg0ire** [comment]
2.13.2 was marked as no longer maintained in d3fcc543c986e133e96b20ab8dc833b5051e8a08, so I'm not sure we will, but maybe we should if something prevents you from upgrading to v3.

**Comment by obstschale** [comment]
Now, that I know where the problem lays I could figure out why it happend now. For our next release we newly require `slm/queue-doctrine 2.0.6`. Currently we cannot upgrade to v3 because we have to support php 7.1. That dependency causes the installation of `doctrine/common v2.13.2`. 

We are investigating in upgrading our minimal requirements to drop support for php 7.1, but I cannot definitly say when this will happen. 

I.e. I would highly appreciate if you could fix this bug. But I do understand the trouble of maintaining old versions especially if already have marked them as no longer maintained.

**Comment by ostrolucky** [comment]
We cannot leave last 2.x broken like this. We could also just revert https://github.com/doctrine/common/pull/869 from 2.x, but since we would have to create new release for 2.x anyway and it's very important to fix this for 3.x at least, we may as well just fix it in both.
