### ISSUE TITLE
ProxyGenerator __set() with return type hint void always returns parent

### ISSUE THREAD

**Issue by GameplayJDK** [doctrine/common#917]
As the title suggests, I noticed that the generated proxy class is breaking my entity when it contains the magic `__set()` method.

As of now the `ProxyGenerator` will always generate a `return parent::__set(...)` call in the proxy class. Example:

(Original entity)
```php
    /**
     * @inheritDoc
     */
    public function __get(string $name)
    {
        return $this->store[$name];
    }

    /**
     * @inheritDoc
     */
    public function __set(string $name, $value): void
    {
        $this->store[$name] = $value;
    }
```

(Proxy entity)
```php
    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get(string $name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set(string $name, $value): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value); // <-- Does not work with 'void' return type.
    }
```

Upon invocation this code will produce the following error message:

> Compile Error: A void function must not return a value

(Original entity, temporary workaround)
```php
    /**
     * @inheritDoc
     */
    public function __get(string $name)
    {
        return $this->store[$name];
    }

    /**
     * @inheritDoc
     */
    public function __set(string $name, $value)/*: void*/
    {
        $this->store[$name] = $value;
    }
```

I'm using `doctrine/common` version `3.0.2`, but I've also checked back on `master`. PHP `8.0.0`, Xdebug `3.0.1`. I've already tracked down the cause of this problem and a bunch of closed issues related to the generated magic methods, listed below.

* https://github.com/doctrine/orm/issues/6221
* https://github.com/doctrine/common/blob/3.1.x/lib/Doctrine/Common/Proxy/ProxyGenerator.php#L593
* https://github.com/doctrine/common/issues/868
* https://github.com/doctrine/common/pull/869/files

As shown by the generated code above and the changes made in the linked PR, the `__get()` magic methods works just fine with return types and also has a check in place to avoid this issue:

```php
            if ($returnTypeHint === ': void') {
                $magicGet .= "\n            return;";
            } else {
                $magicGet .= "\n            return \$this->$name;";
            }
```

I think that check is missing for the `__set()` magic method and it's responsible for this wrong behavior. I'd propose a change to make this:

```php
        if ($hasParentSet) {
            $magicSet .= <<<'EOT'
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

        return parent::__set($name, $value);
EOT;
        } else {
            $magicSet .= "        \$this->\$name = \$value;";
        }
```

into this:

```php
        if ($hasParentSet) {
            $magicSet .= "        \$this->__initializer__ && \$this->__initializer__->__invoke(\$this, '__set', [\$name, \$value]);";

            if ($returnTypeHint === ': void') {
                $magicSet .= <<<'EOT'

        parent::__set($name, $value);
        return;
EOT;
            } else {
                $magicSet .= <<<'EOT'

        return parent::__set($name, $value);
EOT;
            }
        } else {
            $magicSet .= "        \$this->\$name = \$value;";
        }
```

Any thoughts on this? Maybe I'm missing something here.

**Comment by GameplayJDK** [comment]
To bump this topic for a bit, I just noticed that it is perfectly valid to return the result of a parent function returning nothing like:

```php
<?php

class cls_parent
{
  function return_nothing()
  {
    // return nothing
  }
}

class cls_child extends cls_parent
{
  function return_nothing()
  {
    return parent::return_nothing();
  }
}

$cls = new cls_child();

$result = $cls->return_nothing();
var_dump($result);
```

As this [3v4l shows](https://3v4l.org/VH77t) returning nothing gives a `NULL` result, even in PHP 8 this is the case.

But as soon as a type hint of `void` is added, this no longer works with the return. Calling and putting the result into a variable is still fine, but returning somthing in a `void`-method is not. See [this 3v4l](https://3v4l.org/W8diA) for reference.

**Comment by malarzm** [comment]
@GameplayJDK FWIW I took a look at your commit (https://github.com/GameplayJDK/doctrine-common/commit/1583b3fa28305f5845687024684f9172ff6ceb97) and at a glance it looks good and in same spirit as the handling in `__get`. If you could add a test covering the change and make a PR I'll be happy to merge it and release a bugfix version

**Comment by GameplayJDK** [comment]
Hey, thanks for the quick review. I'll add a test asap.
