### ISSUE TITLE
Proxy generator hangs indefinitely when system time is mocked

### ISSUE THREAD

**Issue by valtzu** [doctrine/common#962]
# Bug Report
Proxy generator hangs indefinitely when system time is mocked

Q | A
-- | --
BC Break | no
Version | 2.x/3.x

### Summary

Because `uniqid` relies on system time, when the clock is mocked (e.g. with libfaketime) and it does not advance, calling uniqid more than 1 times will hang up the process indefinitely. This means, when running tests with mocked constant time, the code gets stuck at https://github.com/doctrine/common/blob/c824e95d4c83b7102d8bc60595445a6f7d540f96/lib/Doctrine/Common/Proxy/ProxyGenerator.php#L341

---

### How to reproduce the issue with plain`uniqid`:

```bash
docker build -t php-faketime - <<DOCKERFILE
FROM php:8.1-cli
RUN apt-get update && apt-get install -y libfaketime   
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
DOCKERFILE

docker run --rm -e FAKETIME="2000-02-02 02:02:02" php-faketime -r 'echo uniqid(), PHP_EOL, uniqid();'
``` 

Ideally this would be patched in PHP but I think that won't happen since even the [docs](https://www.php.net/manual/en/function.uniqid.php) mention that `uniqid` is using microtime as random seed, so this is probably considered as a feature and not a bug.

### Possible solutions
I think it would be better to use something like [`tempnam`](https://www.php.net/manual/en/function.tempnam.php), or some other time-independent random function.

---

Related discussion in [libfaketime repository](https://github.com/wolfcw/libfaketime/issues/349).

**Comment by derrabus** [comment]
[`radom_bytes()`](https://www.php.net/random_bytes) would probably be the besser source of randomness in that case. Do you want to work on a PR?
