### ISSUE TITLE
3.4.0 broke class constants defaults in methods parameters when using PHP 8.1+

### ISSUE THREAD

**Issue by kissifrot** [doctrine/common#983]
Hello,

Looks like https://github.com/doctrine/common/commit/a45d43712344ae0f4e1554ddcab39cb5a995e4c3 broke default values using other other references in method parameters:
A class such as
```php

// App\AnotherNamespace\DataType class
<?php
namespace App\AnotherNamespace;

class DataType {
const DAY = 'day';
}


// App\Entity\MyEntity class
<?php
namespace App\Entity;

use App\AnotherNamespace\DataType;
class MyEntity {
public function doSomething(string $dataType = DataType::DAY) {
// Do something
}
```
With 3.3.1:
```php
// App\Entity\MyEntity class
<?php
class MyEntity extends \App\Entity\MyEntity implements \Doctrine\ORM\Proxy\Proxy
public function doSomething(string $dataType = 'day'): void {
}
```

With 3.4.0:
```php
// App\Entity\MyEntity class
<?php
class MyEntity extends \App\Entity\MyEntity implements \Doctrine\ORM\Proxy\Proxy
public function doSomething(string $dataType = App\AnotherNamespace\DataType::DAY): void {
}
```

Which leads to a `Class "App\AnotherNamespace\DataType" does not exist` error, as namespace imports aren't used, or neither global namespace is used.

**Comment by nicolas-grekas** [comment]
Default arguments are going to be quite a pain. See https://3v4l.org/2NEEq for what I mean.
It'd be great if we could have all namespaced symbols have the root `\` prefix, but apparently that's not the case for constants :facepalm:

**Comment by nikic** [comment]
At least for class constants, I agree that the name should be fully qualified.

**Comment by nicolas-grekas** [comment]
Thanks :)
I've opened https://github.com/php/php-src/issues/9447 to keep track of this

**Comment by nicolas-grekas** [comment]
This might allow working around the issue @malarzm:

```php
if (false !== strpos($value, '\\') || false !== strpos($value, '::')) {
    $value = preg_split("/('(?:[^'\\\\]*+(?:\\\\.)*+)*+')/", $value, -1, PREG_SPLIT_DELIM_CAPTURE);
    foreach ($value as $i => $part) {
        if (0 === ($i % 2)) {
            $value[$i] = preg_replace('/(?<![a-zA-Z0-9_\x7f-\xff\\\\])[a-zA-Z0-9_\x7f-\xff]++(?:\\\\[a-zA-Z0-9_\x7f-\xff]++|::)++/', '\\\\\0', $part);
        }
    }
    $value = implode('', $value);
}
```

**Comment by victormacko** [comment]
I've encountered the same issue with class constants, as well as global constants - eg;
Uncaught PHP Exception Error: "Undefined constant "Proxies\__CG__\App\Entity\Member\App\Entity\Member\AUTH_TYPE_ANY""

... where the underlying code is;
public function isAuthorised(
        string $section,
        int $level,
        $type = AUTH_TYPE_ANY) { ... }

**Comment by nicolas-grekas** [comment]
@victormacko good point, I've updated my snippet above.

**Comment by malarzm** [comment]
@kissifrot thanks for the report! Thanks to @nicolas-grekas' snippet I've opened #985 to address the bug. Sorry it took me that long, I was on vacations :)
