### ISSUE TITLE
ProxyGenerator turns double quoted default values into single quoted default values

### ISSUE THREAD

**Issue by ampaze** [doctrine/common#987]
Using PHP 8.1 and doctrine/common 3.4.1

the method in my entity

```php
public function formatAsString(string $rowDelim = "\n"): string
{
}
```

is turned in to
```php
public function formatAsString(string $rowDelim = '\n'): string
{
}
```

in the proxy.

----

Fyi:

This is the version that 3.3.1 generates
```php
public function formatAsString(string $rowDelim = '
'): string
{
}
```

**Comment by malarzm** [comment]
This might be a bug in how PHP is generating default values as 3.4.x started to relying on that. I'll try to have it reproduced later

**Comment by nicolas-grekas** [comment]
This looks like a PHP issue to me, I opened https://github.com/php/php-src/issues/9622
There might be a workaround, to be discovered.

**Comment by malarzm** [comment]
@ampaze as a workaround you could define your method like this:

```
public function formatAsString(string $rowDelim = \PHP_EOL): string
{
}
```

referencing global consts is working good enough with 3.4.1

**Comment by stof** [comment]
@malarzm `\PHP_EOL` is not the same than `"\n"` though

**Comment by malarzm** [comment]
@stof you're right,I thought it was just "good enough" to mention :)
